[package]
name = "letterboxd"
version = "0.2.0"
authors = ["boxdot <d@zerovolt.org>"]
license = "MIT/Apache-2.0"
description = "Letterboxd API provides access to data on the Letterboxd.com website"
repository = "https://github.com/boxdot/letterboxd-rs"
keywords = ["rest", "letterboxd"]
categories = ["api-bindings"]
readme = "README.md"
edition = "2018"

[dependencies]
futures = "0.3"
hex = "0.4.0"
hyper = "=0.13.0-alpha.4"
hyper-tls = "=0.4.0-alpha.4"
rust-crypto = "0.2.36"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
serde_url_params = "0.1.1"
uuid = { version = "0.8.1", features = ["v4"] }
http = "*"
serde_urlencoded = "*"

[dev-dependencies]
tokio-core = "0.1.17"
tokio = "=0.2.0-alpha.6"
