[package]
name = "letterboxd"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]

[dependencies]
futures = "0.1"
hex = "0.2"
hyper = "0.11"
hyper-tls = "0.1"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
uuid = { version = "0.4", features = ["v4"] }
